version: '3.8'
services:
  app:
    image: node:latest 
    volumes:
      - ./server:/workspace
    working_dir: /workspace
    command: "node index.js"
    ports:
      - 4000:4000
  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: e398SDc2
      MONGO_INITDB_DATABASE: plumbus
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: e398SDc2
      ME_CONFIG_MONGODB_URL: mongodb://root:e398SDc2@mongo:27017/
volumes:
  mongo-data:
