version: '3.8'
services:
  app:
    image: node:latest 
    volumes:
      - ./server:/workspace
    working_dir: /workspace
    command: "npm run start:dev"
    ports:
      - 4100:4100
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2d2d2@#d222d22
      POSTGRES_DB: plumbus

volumes:
  postgres-data: