version: '3.8'

services:
  app:
    image: node:latest 
    volumes:
      - ./server:/workspace
    working_dir: /workspace
    command: "npm run start:dev"
    ports:
      - 4100:4100
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    # Uncomment to change startup options
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2d2d2@#d222d22
      POSTGRES_DB: plumbus

    # Add "forwardPorts": ["27017"] to **devcontainer.json** to forward MongoDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  postgres-data: